### ISSUE TITLE
Missing functions Set-ArubaIAPCipherSSL and  Set-ArubaIAPuntrustedSSL

### ISSUE THREAD

**Issue by amnich** [PowerAruba/PowerArubaIAP#1]
Missing function in module Set-ArubaIAPCipherSSL and Set-ArubaIAPuntrustedSSL.
I renamed in the SSL.ps1 your Set-ArubaCXCipherSSL and Set-ArubaCXuntrustedSSL to the mentioned above and it works.

**Comment by alagoutte** [comment]
Oups Thanks, i will fix

**Comment by alagoutte** [comment]
Thanks, it will be fixed on 0.1.1 (released today...)
